# Especialització de DataScience de la IT ACADEMY
### *Exercicis de programació numèrica.*
### *Sprint3 - Tasca M3 T01 - Exercici 1*
#### **Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.**

In [1]:
import numpy as np

In [2]:
#Funció per treure el valors estadistic d'una funció
def estadisticaArray(array):

    if (np.shape(array)[0]) == 1:
        print("Resum estadistic del array")
        print("array: \n",array)            
        print("Valor major del array: ",np.max(array)) #Valor major del array
        print("Valor menor del array: ",np.min(array)) #Valor menor del array
        print("Valor mitja del array: ",np.mean(array)) 
        print("Mitjana del array: ",np.median(array))     
        print("Desviació estandar del array:",np.std(array))
    else:
        print("Error: l'array no es unidimensional")

In [4]:
array1 = 10*np.round(np.random.random((1,20)),3)
array1

array([[4.43, 6.24, 8.47, 3.02, 2.68, 8.23, 1.52, 8.69, 0.36, 4.47, 9.24,
        1.83, 2.03, 4.59, 2.58, 9.81, 4.1 , 3.86, 2.79, 6.87]])

In [5]:
estadisticaArray(array1)

Resum estadistic del array
array: 
 [[4.43 6.24 8.47 3.02 2.68 8.23 1.52 8.69 0.36 4.47 9.24 1.83 2.03 4.59
  2.58 9.81 4.1  3.86 2.79 6.87]]
Valor major del array:  9.81
Valor menor del array:  0.36
Valor mitja del array:  4.7905
Mitjana del array:  4.265
Desviació estandar del array: 2.799972276648467


In [6]:
array2 = np.ones((2,2))
array2

array([[1., 1.],
       [1., 1.]])

In [7]:
estadisticaArray(array2)

Error: l'array no es unidimensional


### *Sprint3 - Tasca M3 T01 - Exercici 2*
#### **Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.**

In [15]:
import numpy as np

def creaArrayNxN(arg):
    array = np.random.randint(0,101, size=(arg,arg))
    return (array)

In [16]:
array = creaArrayNxN (3)
array

array([[40, 83, 71],
       [91, 81, 99],
       [58, 89, 32]])

### *Sprint3 - Tasca M3 T01 - Exercici 3*
#### **Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.**

In [17]:
import numpy as np

def calculaSumaFilasColumnasArray(arr):
    for i in arr:
        print("Suma Fila:",i,"es igual a",np.sum(i))
    arrT = np.transpose(arr)
    for i in arrT:
        print("Suma Columna:",i,"es igual a",np.sum(i))


In [18]:
array

array([[40, 83, 71],
       [91, 81, 99],
       [58, 89, 32]])

In [19]:
calculaSumaFilasColumnasArray(array)

Suma Fila: [40 83 71] es igual a 194
Suma Fila: [91 81 99] es igual a 271
Suma Fila: [58 89 32] es igual a 179
Suma Columna: [40 91 58] es igual a 189
Suma Columna: [83 81 89] es igual a 253
Suma Columna: [71 99 32] es igual a 202


### *Sprint3 - Tasca M3 T01 - Exercici 4*
#### **Implementa manualment una funció que calculi el coeficient de correlació. Informant sobre els seus usos i interpretació.**

In [20]:
arr1 = np.random.randint(0,10, size=(1,3))
arr1

array([[8, 4, 1]])

In [21]:
arr2 = np.random.randint(0,10, size=(1,3))
arr2

array([[7, 9, 4]])

#### Càlcul manual del coeficient de Correlació de Pearson ####
##### Indica la correlació de les dos matrius en rang (-1 a 1): 
##### 1: matrius iguals (correlació total directa)
##### -1: matrius inverses amb igual modul (correlació total inversa)
##### 0: matrius totalment descorrelacionades

In [22]:
import numpy as np
import math

def coeficientCorrelacio(args1,args2):
    #Càlcul valors mitjans
    arrayMedia1 = np.mean(args1) 
    arrayMedia2 = np.mean(args2) 
    
    #Càlcul de les covariances
    arrayCov = np.cov(arr1,arr2)
    
    #Covariança entre arrays 1 i 2
    Cov12 = arrayCov[0,1]
    Cov1 = arrayCov[0,0]
    Cov2 = arrayCov[1,1]
    
    #càlcul del coeficient de Pearson
    coefPearson = Cov12/(math.sqrt(Cov1*Cov2))
    return coefPearson

In [23]:
coefCorrelacio = coeficientCorrelacio(arr1,arr2)
print("Coeficient de correlació dels arrays: ",coefCorrelacio)

Coeficient de correlació dels arrays:  0.5280200004833


In [24]:
coefCorrelacioNumpy = (np.corrcoef(arr1,arr2)[0,1])
print("Coeficient de correlació del arrays: ",coefCorrelacioNumpy)     
#print(np.corrcoef(arr1,arr2))

Coeficient de correlació del arrays:  0.5280200004833001


In [25]:
DiffCoefCorr = coefCorrelacio - coefCorrelacioNumpy
DiffCoefCorr

-1.1102230246251565e-16